### ISSUE TITLE
Cannot decrypt example from paper

### ISSUE THREAD

**Issue by edgarfelizmenio** [ezequiel-umu/node-cp-abe#1]
I tried the encrypting and decrypting a message using the example attributes and policy found in the paper of CP-ABE (https://www.cs.utexas.edu/~bwaters/publications/papers/cp-abe.pdf). From the paper, the algorithm should be able to decrypt the ciphertext.

Here is what I entered in npm.runkit.com. I'm not sure if the problem is with the code or the problem is with the way I used the library.
```js
var nodeCpAbe = require("node-cp-abe");

defaultDate = new Date(parseInt(Date.now()/1000)).getSeconds();
console.log(defaultDate);

k = nodeCpAbe.setup();

kevin_priv_key = 
nodeCpAbe.keygen(k.pubkey, k.mstkey, ["business_staff", "strategy_team", "executive_level = 7", "office = 2362", "hire_date = " + defaultDate]);

ciphertext = nodeCpAbe.encryptMessage(k.pubkey, "(sysadmin and (hire_date < 946702800 or security_team)) or (business_staff and 2 of (executive_level >= 5, audit_group, strategy_team))", new Buffer('asdfghjkl'));
console.log(ciphertext);

kevin_plaintext = nodeCpAbe.decryptMessage(k.pubkey, kevin_priv_key, ciphertext);

console.log(kevin_plaintext);
```

**Comment by ezequiel-umu** [comment]
It seems that comparative rules (like `a < b`, `a = b`...) doesn't work, although that they work in the original CPABE project.

**Comment by edgarfelizmenio** [comment]
I traced the code of the original project. A certain function named parse_attribute in policy_lang.c (cpabe-0.11) must be called for every attribute (see line 100 of keygen.c in cpabe-0.11). It transforms numerical attributes (e.g., security_level = 5) into a collection of string attributes (see paper for details).

The calls to parse_attribute will result to a list of attributes, which will be sorted with strcmp as the comparator, and stored into a char* array. The char* array will then be passed as a parameter to keygen (lines 106-114, and line 129 of keygen.c in cpabe-0.11).

I'm also trying to fix this right now but I'm getting segfault errors. :(

**Comment by edgarfelizmenio** [comment]
#2 I hope this will solve the issue.

**Comment by ezequiel-umu** [comment]
Nice work, merged and fixed.
