### ISSUE TITLE
Node-gyp won't build on Arch Linux

### ISSUE THREAD

**Issue by saadismail** [ezequiel-umu/node-cp-abe#3]
Node-gyp had issues compiling cp-abe on Arch Linux based distro Manjaro Linux. This was due to hard-coded paths for libraries in binding.gyp file.

I fixed it by making the following changes in binding.gyp files:

`
    "include_dirs": [
      ...
      "/usr/lib/glib-2.0/include/"
    ],
    "link_settings": {
      "libraries": [
        ...
        "/usr/lib/libglib-2.0.so.0",
        "/usr/lib/libgmp.so"
      ]
    }
`

I am not sure if I should send a PR for this or this issue should be enough but would be great to mention this in README file. Let me know if I can help documenting this.

Thanks

**Comment by lilezek** [comment]
Hey @saadismail, do you have any suggestion to make it compatible with both systems?
